<div class="row">
    <div class="col-md-12">
    	<div class="card custom-card">
    		<div class="card-header rounded-bottom-0">
    			<h5 class="mt-3">List Calendar</h5>
    		</div>
    		<div class="card-body">
    			<div id="calendar" class="fc fc-media-screen fc-direction-ltr fc-theme-standard"><div class="fc-header-toolbar fc-toolbar fc-toolbar-ltr"><div class="fc-toolbar-chunk"><div class="fc-button-group"><button type="button" title="Previous day" aria-pressed="false" class="fc-prev-button fc-button fc-button-primary"><span class="fc-icon fc-icon-chevron-left"></span></button><button type="button" title="Next day" aria-pressed="false" class="fc-next-button fc-button fc-button-primary"><span class="fc-icon fc-icon-chevron-right"></span></button></div><button type="button" title="Today" aria-pressed="false" class="fc-today-button fc-button fc-button-primary">today</button></div><div class="fc-toolbar-chunk"><h2 class="fc-toolbar-title" id="fc-dom-86">July 12, 2021</h2></div><div class="fc-toolbar-chunk"><div class="fc-button-group"><button type="button" title="list day view" aria-pressed="true" class="fc-listDay-button fc-button fc-button-primary fc-button-active">list day</button><button type="button" title="list week view" aria-pressed="false" class="fc-listWeek-button fc-button fc-button-primary">list week</button></div></div></div><div aria-labelledby="fc-dom-86" class="fc-view-harness fc-view-harness-passive"><div class="fc-list  fc-list-sticky fc-listDay-view fc-view"><div class="fc-scroller" style="overflow: visible;"><table class="fc-list-table "><thead><tr><th scope="col" id="fc-dom-87">Time</th><th scope="col" aria-hidden="true"></th><th scope="col" id="fc-dom-88">Event</th></tr></thead><tbody><tr class="fc-list-day fc-day fc-day-mon fc-day-past" data-date="2021-07-12"><th scope="colgroup" colspan="3" id="fc-dom-89-2021-07-12" aria-labelledby="fc-dom-91"><div class="fc-list-day-cushion fc-cell-shaded"><a id="fc-dom-91" class="fc-list-day-text" title="Go to July 12, 2021" data-navlink="" tabindex="0">Monday</a></div></th></tr><tr class="fc-list-event  fc-event fc-event-past"><td headers="fc-dom-87 fc-dom-89-2021-07-12" class="fc-list-event-time">all-day</td><td aria-hidden="true" class="fc-list-event-graphic"><span class="fc-list-event-dot"></span></td><td headers="fc-dom-88 fc-dom-89-2021-07-12" class="fc-list-event-title"><a>Conference</a></td></tr><tr class="fc-list-event  fc-event fc-event-past"><td headers="" class="fc-list-event-time"></td><td headers="" class="fc-list-event-graphic" aria-hidden="true"><span class="fc-list-event-dot"></span></td><td headers="fc-dom-88 fc-dom-89-2021-07-12" class="fc-list-event-title"><a>Meeting</a></td></tr></tbody></table></div></div></div></div>
    		</div>
    	</div>
    </div>
</div>